# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir R:/work/FORTE/FPGA/fabric/clean/clean/clean.cache/wt [current_project]
set_property parent.project_path R:/work/FORTE/FPGA/fabric/clean/clean/clean.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo r:/work/FORTE/FPGA/fabric/clean/clean/clean.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  R:/work/FORTE/FPGA/fabric/clean/my_lib.vhdl
  R:/work/FORTE/FPGA/fabric/clean/CPU_IO_ConfigMem.vhdl
  R:/work/FORTE/FPGA/fabric/clean/CPU_IO_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/clean/CPU_IO_tile.vhdl
  R:/work/FORTE/FPGA/fabric/clean/IO_1_bidirectional_frame_config.vhdl
  R:/work/FORTE/FPGA/fabric/clean/InPass4_frame_config.vhdl
  R:/work/FORTE/FPGA/fabric/clean/LUT4AB_ConfigMem.vhdl
  R:/work/FORTE/FPGA/fabric/clean/LUT4AB_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/clean/LUT4AB_tile.vhdl
  R:/work/FORTE/FPGA/fabric/clean/LUT4c_frame_config.vhdl
  R:/work/FORTE/FPGA/fabric/clean/MUX8LUT_frame_config.vhdl
  R:/work/FORTE/FPGA/fabric/clean/N_term_single_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/clean/N_term_single_tile.vhdl
  R:/work/FORTE/FPGA/fabric/clean/OutPass4_frame_config.vhdl
  R:/work/FORTE/FPGA/fabric/clean/S_term_single_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/clean/S_term_single_tile.vhdl
  R:/work/FORTE/FPGA/fabric/clean/W_IO_ConfigMem.vhdl
  R:/work/FORTE/FPGA/fabric/clean/W_IO_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/clean/W_IO_tile.vhdl
  R:/work/FORTE/FPGA/fabric/clean/config_UART.vhd
  R:/work/FORTE/FPGA/fabric/clean/eFPGA_top.vhd
  R:/work/FORTE/FPGA/fabric/clean/fabric.vhdl
  R:/work/FORTE/FPGA/fabric/clean/emulation_wrapper_top.vhd
  R:/work/FORTE/FPGA/fabric/clean/MUX8LUT.vhdl
}
read_ip -quiet R:/work/FORTE/FPGA/fabric/clean/clean/clean.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all r:/work/FORTE/FPGA/fabric/clean/clean/clean.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all r:/work/FORTE/FPGA/fabric/clean/clean/clean.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all r:/work/FORTE/FPGA/fabric/clean/clean/clean.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc R:/work/FORTE/FPGA/fabric/clean/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files R:/work/FORTE/FPGA/fabric/clean/Nexys-4-DDR-Master.xdc]


synth_design -top emulation_wrapper_top -part xc7a100tcsg324-2 -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef emulation_wrapper_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file emulation_wrapper_top_utilization_synth.rpt -pb emulation_wrapper_top_utilization_synth.pb"
