# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir R:/work/FORTE/FPGA/fabric/vivado2/project_1.cache/wt [current_project]
set_property parent.project_path R:/work/FORTE/FPGA/fabric/vivado2/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo r:/work/FORTE/FPGA/fabric/vivado2/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  R:/work/FORTE/FPGA/fabric/my_lib.vhdl
  R:/work/FORTE/FPGA/fabric/W_IO_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/S_term_single_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/OutPass4_frame_config.vhdl
  R:/work/FORTE/FPGA/fabric/N_term_single_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/LUT4AB_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/IO_1_bidirectional_frame_config.vhdl
  R:/work/FORTE/FPGA/fabric/InPass4_frame_config.vhdl
  R:/work/FORTE/FPGA/fabric/CPU_IO_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/W_IO_tile.vhdl
  R:/work/FORTE/FPGA/fabric/S_term_single_tile.vhdl
  R:/work/FORTE/FPGA/fabric/N_term_single_tile.vhdl
  R:/work/FORTE/FPGA/fabric/LUT4AB_tile.vhdl
  R:/work/FORTE/FPGA/fabric/CPU_IO_tile.vhdl
  R:/work/FORTE/FPGA/fabric/fabric.vhdl
  R:/work/FORTE/FPGA/fabric/W_term_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/W_term_single_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/E_term_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/E_term_single_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/W_term_tile.vhdl
  R:/work/FORTE/FPGA/fabric/W_term_single_tile.vhdl
  R:/work/FORTE/FPGA/fabric/OutPassRES2.vhdl
  R:/work/FORTE/FPGA/fabric/OutPassRES1.vhdl
  R:/work/FORTE/FPGA/fabric/OutPassRES0.vhdl
  R:/work/FORTE/FPGA/fabric/OutPass4.vhdl
  R:/work/FORTE/FPGA/fabric/MUX8LUT_latch_config.vhdl
  R:/work/FORTE/FPGA/fabric/MUX8LUT.vhdl
  R:/work/FORTE/FPGA/fabric/LUT4c_latch_config.vhdl
  R:/work/FORTE/FPGA/fabric/LUT4c.vhdl
  R:/work/FORTE/FPGA/fabric/IO_1_bidirectional.vhdl
  R:/work/FORTE/FPGA/fabric/InPassOPB.vhdl
  R:/work/FORTE/FPGA/fabric/InPassOPA.vhdl
  R:/work/FORTE/FPGA/fabric/InPassFlop2.vhdl
  R:/work/FORTE/FPGA/fabric/E_term_tile.vhdl
  R:/work/FORTE/FPGA/fabric/E_term_single_tile.vhdl
  R:/work/FORTE/FPGA/fabric/CPU_IO_ConfigMem.vhdl
  R:/work/FORTE/FPGA/fabric/LUT4AB_ConfigMem.vhdl
  R:/work/FORTE/FPGA/fabric/eFPGA_top.vhd
  R:/work/FORTE/FPGA/fabric/LUT4c_frame_config.vhdl
  R:/work/FORTE/FPGA/fabric/MUX8LUT_frame_config.vhdl
  R:/work/FORTE/FPGA/fabric/W_IO_ConfigMem.vhdl
  R:/work/FORTE/FPGA/fabric/config_UART.vhd
  R:/work/FORTE/FPGA/fabric/vivado2/project_1.srcs/sources_1/new/emulation_wrapper_top.vhd
  R:/work/FORTE/FPGA/fabric/IO_1_bidirectional_frame_config_pass.vhdl
  R:/work/FORTE/FPGA/fabric/N_term_single2_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/RegFile_tile.vhdl
  R:/work/FORTE/FPGA/fabric/N_term_single2_tile.vhdl
  R:/work/FORTE/FPGA/fabric/RegFile_32x4.vhdl
  R:/work/FORTE/FPGA/fabric/RegFile_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/S_term_single2_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/S_term_single2_tile.vhdl
  R:/work/FORTE/FPGA/fabric/RegFile_ConfigMem.vhdl
  R:/work/FORTE/FPGA/fabric/DSP_bot_tile.vhdl
  R:/work/FORTE/FPGA/fabric/DSP_bot_ConfigMem.vhdl
  R:/work/FORTE/FPGA/fabric/DSP_top_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/DSP_bot_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/MULADD.vhdl
  R:/work/FORTE/FPGA/fabric/DSP_top_ConfigMem.vhdl
  R:/work/FORTE/FPGA/fabric/DSP_top_tile.vhdl
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top eFPGA_top -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef eFPGA_top.dcp

catch { report_utilization -file eFPGA_top_utilization_synth.rpt -pb eFPGA_top_utilization_synth.pb }
