version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

python:
  # Install our python package before building the docs
  install:
    - requirements: docs/requirements.txt
  
#conda:
#  environment: docs/environment.yml

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
  
formats:
  - pdf
  - epub
