cp ../fabric/IO_1_bidirectional.vhdl ./
cp ../fabric/IO_1_bidirectional_frame_config_pass.vhdl ./
cp ../fabric/LUT4c_latch_config.vhdl ./
cp ../fabric/LUT4c_frame_config.vhdl ./
cp ../fabric/MUX8LUT_latch_config.vhdl ./
cp ../fabric/MUX8LUT_frame_config.vhdl ./
cp ../fabric/InPassOPA.vhdl ./
cp ../fabric/InPass4_frame_config.vhdl ./
cp ../fabric/InPassOPB.vhdl ./
cp ../fabric/OutPassRES0.vhdl ./
cp ../fabric/OutPassRES1.vhdl ./
cp ../fabric/OutPassRES2.vhdl ./
cp ../fabric/OutPass4_frame_config.vhdl ./
cp ../fabric/RegFile_32x4.vhdl ./
cp ../fabric/MULADD.vhdl ./
cp ../fabric/*.list ./
cp ../fabric/CPU_IO_ConfigMem.csv ./
cp ../fabric/DSP_bot_ConfigMem.csv ./
cp ../fabric/DSP_top_ConfigMem.csv ./
cp ../fabric/LUT4AB_ConfigMem.csv ./
cp ../fabric/RegFile_ConfigMem.csv ./
cp ../fabric/W_IO_ConfigMem.csv ./
cp ../fabric/verilog_base/*.v ./
