# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbg484-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir R:/work/FORTE/FPGA/fabric/vivado/test_fabric.cache/wt [current_project]
set_property parent.project_path R:/work/FORTE/FPGA/fabric/vivado/test_fabric.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo r:/work/FORTE/FPGA/fabric/vivado/test_fabric.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  R:/work/FORTE/FPGA/fabric/test.vhd
  R:/work/FORTE/FPGA/fabric/CLB_switch_matrix.VHDL
  R:/work/FORTE/FPGA/fabric/clb_slice_4xLUT4.vhdl
  R:/work/FORTE/FPGA/fabric/clb_tile.vhdl
  R:/work/FORTE/FPGA/fabric/IO_4_bidirectional.vhdl
  R:/work/FORTE/FPGA/fabric/IO_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/IO_tile.vhdl
  R:/work/FORTE/FPGA/fabric/N_term_tile.vhdl
  R:/work/FORTE/FPGA/fabric/E_term_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/S_term_tile.vhdl
  R:/work/FORTE/FPGA/fabric/W_term_tile.vhdl
  R:/work/FORTE/FPGA/fabric/E_term_tile.vhdl
  R:/work/FORTE/FPGA/fabric/S_term_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/N_term_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/W_term_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/S_term_IO_tile.vhdl
  R:/work/FORTE/FPGA/fabric/N_term_IO_tile.vhdl
  R:/work/FORTE/FPGA/fabric/S_term_IO_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/N_term_IO_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/clb_slice_2xLUT4.vhdl
  R:/work/FORTE/FPGA/fabric/LUT4AB_switch_matrix.vhdl
  R:/work/FORTE/FPGA/fabric/LUT4c.vhdl
  R:/work/FORTE/FPGA/fabric/LUT4AB_tile.vhdl
  R:/work/FORTE/FPGA/fabric/MUX8LUT.vhdl
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top LUT4AB -part xc7k70tfbg484-3 -flatten_hierarchy none


write_checkpoint -force -noxdef LUT4AB.dcp

catch { report_utilization -file LUT4AB_utilization_synth.rpt -pb LUT4AB_utilization_synth.pb }
